### PR TITLE
Handle image files

### PR DESCRIPTION
**Pull request by hargup**
Handle image files while fetching data.

### CODE REVIEW

**Comment by hargup** [comment]
Master gives an error as it tries to parse everything it fetches as json.

**Comment by hargup** [comment]
@jgorset Can you help me fix the errors I'm encountering with the tests?

**Comment by jgorset** [comment]
Sorry for not getting around to this, @hargup.

> Master gives an error while fetching picture files as it tries to parse everything it fetches as json.

Is this a typo? I think you mean to say that it tries to decode bytes as UTF-8?

**Comment by jgorset** [comment]
I believe the tests are failing because you're only parsing JSON for responses that are bytes. The tests are not returning bytes, though, but rather strings, and so they never get parsed.

It's been a while, but I believe we did that for interoperability with Python 2.x and 3.x. I changed it to try to decode UTF-8 and parse as JSON in separate operations, each falling back to just returning the data if they fail.

**Comment by jgorset** [comment]
Thanks for your contribution!

**Pull request merged**
